wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1652269071
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      4: 3.9.5
      5: 0.12.14
      8:
      - 3
      - 5
